# Generated by Django 4.0.2 on 2022-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=1, max_digits=4)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
