# Generated by Django 4.0.2 on 2022-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_tarea_usuario_tarea_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
